apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: root-gateway
  # namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.fleetman.com"   # Domain name of the external website
    - "fleetman.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: root-gateway-vs
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - root-gateway
  http:
  - route:
    - destination:
        host: fleetman-webapp
---
